name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download and extract OpenSSL
        run: |
          curl -L "https://downloads.sourceforge.net/project/openssl-for-windows/OpenSSL-1.1.1h_win32%28static%29%5BNo-GOST%5D.zip" -o openssl.zip

      - name: Inject version
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          python -c "import os; v = '${{ github.ref_name }}'; open('app/version.py', 'w').write(f'__version__ = \"{v.lstrip(\"v\")}\"')"

      - name: Build executable
        run: python build.py

      - name: Rename executable logic
        run: |
          cd dist
          mv Hi10-DL.exe Hi10-DL-${{ github.ref_name }}.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Hi10-DL-${{ github.ref_name }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
